### ISSUE TITLE
[eWeLink] WebSocket messge received:  {"error":400,"reason":"Bad Request"

### ISSUE THREAD

**Issue by gcorly** [howanghk/homebridge-ewelink#121]
Hi,

since yesterday I have an issue with ewelink plugin

I have this message : "[eWeLink] WebSocket messge received:  {"error":400,"reason":"Bad Request","apikey":"xxxxx","sequence":"xxxxx","actionName":"userOnline"}

No change has been made : 
Homebridge version v1.2.3

Plugins installed
Homebridge UI
homebridge-config-ui-x v4.31.0

Homebridge Ewelink Max
homebridge-ewelink-max v0.1.24

**Comment by gcorly** [comment]
Just another comment, you may correct the message :"[eWeLink] WebSocket messge received" with ""[eWeLink] WebSocket message received"

**Comment by gcorly** [comment]
Try to a stop an equipment

[2020-11-2 18:48:53] [eWeLink] Setting power state to [off] for device [PC 2]
[2020-11-2 18:48:53] [eWeLink] Requesting power state for [PC 2]
[2020-11-2 18:48:53] [eWeLink] WebSocket messge received:  {"error":406,"sequence":"1604339333126"}
[2020-11-2 18:48:53] [eWeLink] WebSocket was closed. Reason [1006]
[2020-11-2 18:48:53] [eWeLink] API reported that [PC 2] is On
[2020-11-2 18:48:55] [eWeLink] Requesting power state for [Lampe (SONOFF 1)]
[2020-11-2 18:48:55] [eWeLink] Requesting power state for [Guirlande (SONOFF2)]
[2020-11-2 18:48:55] [eWeLink] Requesting power state for [Lanterne (SONOFF4)]
[2020-11-2 18:48:55] [eWeLink] Requesting power state for [PC 1]
[2020-11-2 18:48:55] [eWeLink] Requesting power state for [PC 2]
[2020-11-2 18:48:55] [eWeLink] Requesting power state for [New1]
[2020-11-2 18:48:55] [eWeLink] Requesting power state for [New2]
[2020-11-2 18:48:55] [eWeLink] Requesting power state for [New3]
[2020-11-2 18:48:55] [eWeLink] Sonoff API 503 error
[2020-11-2 18:48:55] [eWeLink] Sonoff API 503 error
[2020-11-2 18:48:55] [eWeLink] API reported that [PC 2] is On

**Comment by Patdic54** [comment]
Same problem

**Comment by bwp91** [comment]
https://github.com/howanghk/homebridge-ewelink/issues/120#issuecomment-718543377

**Comment by gcorly** [comment]
solved by uninstalling this plugin for me, and installing ewelink homebridge (verified)

**Comment by entavio** [comment]
Not working for me..... no error any more but I still can’t control the sonoff

**Comment by lee7578kimo** [comment]
I build a new homebirdge with homebridge-ewelink
need change "email" to "username" in config.json
works fine now
not sure whether necessary to pay and upgrade ewelink account to Pro. I just paid.

**Comment by entavio** [comment]
After second reinstall / reconfigure now it works :-)

**Comment by migabc** [comment]
Any change of fixing this issue (400 - bad request) on this plugin (homebridge-ewelink-max)?
Or, alternatively allow the other plugin (homebridge-ewelink) to run under the stable/wanted version of homebridge 0.4.53

I tried to swap the homebridge-ewelink-max for the homebridge-ewelink but this plugin requires HomeBridge version >=1.0.0 and I'm currently using homebridge v0.4.53 (because homebridge-knx only runs on this stable version of homebridge)

So it seems I am stuck :-(

pi@raspberrypi:~ $ date; npm outdated -g --depth=0
Sat Nov 7 08:55:53 WET 2020
Package Current Wanted Latest Location
hap-nodejs 0.4.53 0.4.53 0.8.2 global
homebridge 0.4.53 0.4.53 1.1.6 global
homebridge-camera-ffmpeg 0.1.19 0.1.19 3.0.3 global

pi@raspberrypi:~ $ date; npm list --depth=0 -g
Sat Nov 7 09:31:26 WET 2020
/usr/lib
├── hap-nodejs@0.4.53
├── homebridge@0.4.53
├── homebridge-bmw-connected@1.0.0
├── homebridge-broadlink-rm@3.6.22
├── homebridge-camera-ffmpeg@0.1.19
├── homebridge-ewelink-max@0.1.24
├── homebridge-gpio-blinds@1.0.0
├── homebridge-gpio-device@0.4.6
├── homebridge-knx@0.3.27
├── homebridge-yeelight-wifi@2.2.2
├── node-gyp@7.1.2
├── npm@6.14.8
└── request@2.88.2

pi@raspberrypi:~ $

Any help appreciated
